### ISSUE TITLE
Cant find config file

### ISSUE THREAD

**Issue by jayvdb** [helixbass/tree-sitter-lint#86]
I run this and see
```
> ~/.cargo/bin/tree-sitter-lint --help
thread 'main' panicked at src/config/config_file.rs:83:6:
Couldn't find config file
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jayvdb** [comment]
And if I look at https://github.com/helixbass/tree-sitter-lint-plugin-typescript-eslint/blob/master/.tree-sitter-lint.yml 

I think I can do

```
> cargo install --git https://github.com/helixbass/tree-sitter-lint-plugin-rust-known-imports
    Updating git repository `https://github.com/helixbass/tree-sitter-lint-plugin-rust-known-imports`
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), 652 bytes | 108.00 KiB/s, done.
From https://github.com/helixbass/tree-sitter-lint-plugin-rust-known-imports
 * [new ref]         HEAD       -> origin/HEAD
error: no packages found with binaries or examples
```

**Comment by jayvdb** [comment]
If I do create a config file, I get
```
> ~/.cargo/bin/tree-sitter-lint
Config changed, regenerating local binary
thread 'main' panicked at src/cli.rs:164:9:
Cargo release build of local binary project failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But if I go to the souce directory I built it from, this works
```
~/rust/tree-sitter-lint> cargo build --release --bin tree-sitter-lint
    Finished `release` profile [optimized] target(s) in 0.17s
```

**Comment by jayvdb** [comment]
Ok, I think I see the problem

It is assuming that it can find my local clone of `tree-sitter-lint` at `../../../tree-sitter-lint`

```
~/work/my-monorepo/.tree-sitter-lint/tree-sitter-lint-local> cargo build --release --bin tree-sitter-lint-local
error: failed to load manifest for dependency `tree-sitter-lint`

Caused by:
  failed to read `/home/jayvdb/work/tree-sitter-lint/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by jayvdb** [comment]
And after waiting a long time for a `--release` build to build swift,objc,other-undesirable-lang, I get

```
   Compiling tree-sitter-lint-local v0.1.0 (/home/jayvdb/work/rosalind/.tree-sitter-lint/tree-sitter-lint-local)
error[E0433]: failed to resolve: could not find `ProvidedTypes` in `tree_sitter_lint_plugin_rust_known_imports`
 --> src/lib.rs:1:3922
  |
1 | ...plugin_rust_known_imports :: ProvidedTypes :: < 'a > :: once_lock_storage () , tree_sitter_lint_plugin_rustfmt_provided_instances : tree_sitter_lint_p...
  |                                 ^^^^^^^^^^^^^ could not find `ProvidedTypes` in `tree_sitter_lint_plugin_rust_known_imports`

error[E0433]: failed to resolve: could not find `ProvidedTypes` in `tree_sitter_lint_plugin_rustfmt`
 --> src/lib.rs:1:4060
  |
1 | ...ree_sitter_lint_plugin_rustfmt :: ProvidedTypes :: < 'a > :: once_lock_storage () }) } } struct FromFileRunContextInstanceProviderLocal < 'a > { tree_...
  |                                      ^^^^^^^^^^^^^ could not find `ProvidedTypes` in `tree_sitter_lint_plugin_rustfmt`

error[E0425]: cannot find function `instantiate` in crate `tree_sitter_lint_plugin_rust_known_imports`
 --> src/lib.rs:1:3375
  |
1 | ...itter_lint_plugin_rust_known_imports :: instantiate () , tree_sitter_lint_plugin_rustfmt :: instantiate ()] } fn all_standalone_rules () -> Vec < Arc ...
  |                                            ^^^^^^^^^^^ not found in `tree_sitter_lint_plugin_rust_known_imports`

error[E0425]: cannot find function `instantiate` in crate `tree_sitter_lint_plugin_rustfmt`
 --> src/lib.rs:1:3427
  |
1 | ...tiate () , tree_sitter_lint_plugin_rustfmt :: instantiate ()] } fn all_standalone_rules () -> Vec < Arc < dyn Rule >> { vec ! [] } struct FromFileRunC...
  |                                                  ^^^^^^^^^^^ not found in `tree_sitter_lint_plugin_rustfmt`

error[E0412]: cannot find type `ProvidedTypes` in crate `tree_sitter_lint_plugin_rust_known_imports`
 --> src/lib.rs:1:4283
  |
1 | ...tter_lint_plugin_rust_known_imports :: ProvidedTypes :: < 'a > as FromFileRunContextProvidedTypes :: < 'a >> :: OnceLockStorage , tree_sitter_lint_plu...
  |                                           ^^^^^^^^^^^^^ not found in `tree_sitter_lint_plugin_rust_known_imports`

error[E0412]: cannot find type `ProvidedTypes` in crate `tree_sitter_lint_plugin_rustfmt`
 --> src/lib.rs:1:4464
  |
1 | ...ances : < tree_sitter_lint_plugin_rustfmt :: ProvidedTypes :: < 'a > as FromFileRunContextProvidedTypes :: < 'a >> :: OnceLockStorage } impl < 'a > Fr...
  |                                                 ^^^^^^^^^^^^^ not found in `tree_sitter_lint_plugin_rustfmt`
```

**Comment by helixbass** [comment]
Ya sorry there is likely some stuff hard-coded currently this crate isn't totally "ready for public consumption" yet

That being said, it is cool that you are trying to get this up and running and I'm happy to try and help you get it set up

**Comment by helixbass** [comment]
The errors on the `--release` build I think are that there is a (currently undocumented) "contract" that a plugin's `src/lib.rs` is supposed to "expose", and I think that contract (as expected by the current `master` branch of `tree-sitter-lint`) is not currently satisfied on the `master` branch of `tree-sitter-lint-plugin-rustfmt` or `tree-sitter-lint-plugin-rust-known-imports`

So if you want to use those plugins (which are currently in a _significantly_ unstable state - the idea with `plugin-rustfmt` is to have something like `eslint-plugin-prettier` which runs `rustfmt` as a lint rule but I think it currently gets confused rather often at least in the in-editor LSP environment; `plugin-rust-known-imports` is an attempt to mimic [`eslint-plugin-known-imports`](github.com/helixbass/eslint-plugin-known-imports) and do auto-generation/-removal of `use` statements in Rust code, but it is _very shaky_ (and possibly a fundamentally bad idea)) I think you'd need to check out other branches of those repos

Specifically looking at my local setup I think you need:

The `generic-type` branch checked out for `tree-sitter-lint-plugin-rust-known-imports`

The `rustfmt-rule` branch checked out for `tree-sitter-lint-plugin-rustfmt`

**Comment by helixbass** [comment]
Basically ya I think you want to try and run against Git checkouts of all of these repos where they all live as "sibling" directories (as opposed to doing eg `cargo install`)

And yes the rough architecture of `tree-sitter-lint` is that it generates a custom local binary "per-project". So you'd have a `.tree-sitter-lint.yml` file in a project root that describes which tree-sitter-lint plugins and rules you want to use for that project (vaguely mimicking an ESLint config file eg `.eslintrc.yml`). And then running `tree-sitter-lint` (which currently I'd invoke by doing a local `--release` build of I guess the `master` branch of a Git checkout of the `tree-sitter-lint` repo and then running that release build binary from the project root where you have a `.tree-sitter-lint.yml` file) should rather clumsily detect that it needs to (re-)generate a new custom local binary which it will put under `.tree-sitter-lint/tree-sitter-lint-local/` I believe. And then it runs that local `.tree-sitter-lint/tree-sitter-lint-local/target/release/tree-sitter-lint-local` or whatever to actually perform the running of the specified lint rules against the project files

If you wanted to try running in-editor via LSP that is also somewhat possible currently but requires a little bit of manual setup

**Comment by helixbass** [comment]
Ah also per the issue you just opened on `tree-sitter-grep` I think (until yes I could probably merge that `tree-sitter-grep` PR) you want to have the `run-context-tree-sitter-lint` branch of the `tree-sitter-grep` repo checked out locally

And it looks like I have the `update-tree-sitter-grep-dependency` branch of the `tree-sitter-lint` repo checked out locally as well

(I haven't worked on `tree-sitter-lint` for a couple months so don't remember exactly what the status some of this was)

**Comment by jayvdb** [comment]
No rush on any of this.  I'm just documenting my experience in this cool little labyrinth.
IMO getting a fixed version of tree-sitter-grep released is more important as that is quite usable as-is.  And yes, it is surprisingly fast.
